name: build-ocp
channels:
  - conda-forge
dependencies:
  - python=__PY_VERSION__
  - setuptools>=75
  - pybind11=2.13.*
  - pybind11-stubgen
  - pip
  - pip: 
    - build
    - wheel
    - __WHEEL_REPAIR__
  