name: build-ocp
channels:
  - conda-forge
dependencies:
  - python=3.13
  - setuptools>=75
  - pybind11=2.13.*
  - cmake >3.24
  - ninja
  - clang==15.0.7
  - llvmdev==15.0.7
  - tbb-devel
  - pybind11-stubgen
  - rapidjson
  